#ifndef FORWARDER_LOG_HH
#define FORWARDER_LOG_HH

#include "soil/Log.hh"

#define FORWARDER_LOG_INIT(x) SOIL_LOG_INIT(x)

#define FORWARDER_TRACE SOIL_TRACE
#define FORWARDER_DEBUG SOIL_DEBUG
#define FORWARDER_INFO  SOIL_INFO
#define FORWARDER_WARNING SOIL_WARNING
#define FORWARDER_ERROR SOIL_ERROR
#define FORWARDER_FATAL SOIL_FATAL
#define FORWARDER_PDU SOIL_PDU
#define FORWARDER_CUSTOM SOIL_CUSTOM


#endif

