// Copyright (c) 2010
// All rights reserved.

#ifndef STREAMER_LOG_HH
#define STREAMER_LOG_HH

#include "soil/Log.hh"

#define STREAMER_LOG_INIT(x) SOIL_LOG_INIT(x)

#define STREAMER_TRACE SOIL_TRACE
#define STREAMER_DEBUG SOIL_DEBUG
#define STREAMER_INFO  SOIL_INFO
#define STREAMER_WARNING SOIL_WARNING
#define STREAMER_ERROR SOIL_ERROR
#define STREAMER_FATAL SOIL_FATAL
#define STREAMER_PDU SOIL_PDU
#define STREAMER_CUSTOM SOIL_CUSTOM


#endif

